export enum ProficiencyLevel {
  RECREATIONAL = 'RECREATIONAL',
  MIDDLE_SCHOOL_C_TEAM = 'MIDDLE_SCHOOL_C_TEAM',
  MIDDLE_SCHOOL_JV = 'MIDDLE_SCHOOL_JV',
  MIDDLE_SCHOOL_VARSITY = 'MIDDLE_SCHOOL_VARSITY',
  HIGH_SCHOOL_C_TEAM = 'HIGH_SCHOOL_C_TEAM',
  HIGH_SCHOOL_JV = 'HIGH_SCHOOL_JV',
  HIGH_SCHOOL_VARSITY = 'HIGH_SCHOOL_VARSITY'
}
